'use client';
import { Textarea } from '@/components/ui/textarea';
import { useParams, useRouter } from 'next/navigation';
import { Form, FormControl, FormField, FormItem } from '@/components/ui/form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { toast } from '@/components/ui/use-toast';
import { Button } from '@/components/ui/button';
import { messageSchema } from '@/validations/messageSchema';
import axios, { AxiosError } from 'axios';
import { ApiResponse } from '@/types/ApiResponse';
import dynamic from 'next/dynamic';
const SuggestMessages = dynamic(() => import('@/components/SuggestMessages'));

function UsernamePage() {
  const params = useParams();
  const router = useRouter();

  const form = useForm<z.infer<typeof messageSchema>>({
    resolver: zodResolver(messageSchema),
    defaultValues: {
      content: '',
    },
  });

  const {
    reset,
    control,
    handleSubmit,
    setValue,
    formState: { errors },
  } = form;

  async function onSubmit(data: z.infer<typeof messageSchema>) {
    try {
      const response = await axios.post<ApiResponse>(`/api/send-message`, {
        content: data.content,
        username: params.username,
      });
      toast({
        title: 'Success',
        description: (
          <pre className="mt-2 w-[340px] rounded-md bg-slate-950 p-4">
            <code className="text-white">{response.data.message}</code>
          </pre>
        ),
      });
      reset(); // Attempt to reset the form
    } catch (error) {
      console.error('Error in signup of user', error);
      const axiosError = error as AxiosError<ApiResponse>;
      let errorMessage = axiosError.response?.data?.message;
      toast({
        title: 'Error',
        description: errorMessage,
        variant: 'destructive',
      });
    }
  }

  return (
    <main className="flex flex-col">
      <div className="text-3xl md:text-4xl font-bold text-center mt-6">
        Public Profile Link
      </div>
      <div className="text-lg text-center mt-4 p-2">
        Send anonymous message to {params.username}
      </div>
      <Form {...form}>
        <form
          onSubmit={handleSubmit(onSubmit)}
          className="mt-8 w-svw space-y-6 flex flex-col justify-center items-center"
        >
          <FormField
            control={control}
            name="content"
            render={({ field }) => (
              <FormItem className="w-full flex justify-center">
                <FormControl>
                  <Textarea
                    {...field}
                    placeholder="Write a message anonymously"
                    id="message"
                    className="w-2/3 h-24"
                  />
                </FormControl>
              </FormItem>
            )}
          />
          {errors.content && (
            <p className="text-red-500">{errors.content.message}</p>
          )}
          <Button type="submit" className="w-60 md:w-32">
            Send Message
          </Button>
        </form>
      </Form>

      <div className="flex justify-center mt-4">
        <SuggestMessages
          setValue={setValue}
          Button={
            <Button
              className="p-4 mt-12"
              onClick={() =>
                toast({
                  title:
                    'Messages would be generated by AI once openAPI key added',
                })
              }
            >
              {' '}
              Suggest Messages{' '}
            </Button>
          }
        />
      </div>

      <div className="mt-12 text-center">Get Your Message Board</div>
      <div className="flex justify-center mt-4">
        <Button className="p-4" onClick={() => router.push('/signup')}>
          Create Your Account
        </Button>
      </div>
    </main>
  );
}

export default UsernamePage;
